# Header
menu:
  主页: /
  所有文章: /archives
  #随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/luckymrwang"
  weibo: "http://weibo.com/iuckymrwang"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: 阅读更多
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
#google_analytics: ''
favicon: /favicon.png

#你的头像url
#avatar:
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# DuoShuo
duoshuo: luckymrwang

#baidu_analytics
baidu_analytics: ec2a44ace31b8d8b179065de4a6565cd

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification: RI5hZTIk8g_rDngCzxDBUrJ9IfGA4gOrceVlc-6OUW0


# Google Analytics
# Google分析ID
google_analytics: UA-68490584-1

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends: false

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 一天一点进步...