# Logo
logo: css/images/logo.png # Empty this to unset logo

# Header
menu:
  主页: .
  文章列表: archives
  #分类: categories
  #标签: tags
  关于: about

# Content
excerpt_link: 阅读更多
fancybox: true

# Profile
profile: true # whether to show profile bar
gravatar: false # whether to use gravatar with the email
showlogo: false # whether to show the logo in the header

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
#- recent_posts
#- category
- tag
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  github: https://github.com/luckymrwang
  weibo: http://weibo.com/iuckymrwang
  #douban: '#'
  #zhihu: "#"
  twitter: 'javascript:void(0);'
  facebook: 'javascript:void(0);'
  #dribbble: '#'
  #rss: atom.xml

# Links
links:
  Hexo: http://hexo.io

# CDN
cdn: useso #If your site loads slowly change it to "google" , because "useso" is slow out of China

# Miscellaneous
google_site_verification:
google_analytics: true
baidu_analytics: true
favicon: favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
